SEASON = "2024-25"
SEASON_YEAR = "2024"

TENDENCIES = [
    {"order": 1,  "name": "Shot",                          "hard_cap": 75, "notes": "Usage tendency"},
    {"order": 2,  "name": "Touch",                         "hard_cap": 65, "notes": "Involvement/priority"},
    {"order": 3,  "name": "Shot Close",                    "hard_cap": 60, "notes": "3-10 ft shots"},
    {"order": 4,  "name": "Shot Under",                    "hard_cap": 60, "notes": "Point-blank/rim finishes"},
    {"order": 5,  "name": "Shot Close Left",               "hard_cap": 50, "notes": "Close left zone"},
    {"order": 6,  "name": "Shot Close Middle",             "hard_cap": 50, "notes": "Close middle zone"},
    {"order": 7,  "name": "Shot Close Right",              "hard_cap": 50, "notes": "Close right zone"},
    {"order": 8,  "name": "Shot Mid",                      "hard_cap": 55, "notes": "Master gate for mid-range"},
    {"order": 9,  "name": "Spot-Up Shot Mid",              "hard_cap": 45, "notes": "Rule: <= Shot Mid"},
    {"order": 10, "name": "Off-Screen Mid",                "hard_cap": 40, "notes": "Rule: <= Shot Mid"},
    {"order": 11, "name": "Shot Mid Left",                 "hard_cap": 45, "notes": "Mid-range left zone"},
    {"order": 12, "name": "Shot Mid Left-Center",          "hard_cap": 45, "notes": "Mid-range left-center zone"},
    {"order": 13, "name": "Shot Mid Center",               "hard_cap": 45, "notes": "Mid-range center zone"},
    {"order": 14, "name": "Shot Mid Right-Center",         "hard_cap": 45, "notes": "Mid-range right-center zone"},
    {"order": 15, "name": "Shot Mid Right",                "hard_cap": 45, "notes": "Mid-range right zone"},
    {"order": 16, "name": "Shot Three",                    "hard_cap": 60, "notes": "Overall 3PT willingness"},
    {"order": 17, "name": "Spot-Up Three",                 "hard_cap": 60, "notes": "Catch-and-shoot 3PT"},
    {"order": 18, "name": "Off-Screen Three",              "hard_cap": 55, "notes": "Screen-read 3PT"},
    {"order": 19, "name": "Shot Three Left",               "hard_cap": 50, "notes": "Three-point left corner zone"},
    {"order": 20, "name": "Shot Three Left-Center",        "hard_cap": 50, "notes": "Three-point left-center zone"},
    {"order": 21, "name": "Shot Three Center",             "hard_cap": 50, "notes": "Three-point center zone"},
    {"order": 22, "name": "Shot Three Right-Center",       "hard_cap": 50, "notes": "Three-point right-center zone"},
    {"order": 23, "name": "Shot Three Right",              "hard_cap": 50, "notes": "Three-point right corner zone"},
    {"order": 24, "name": "Contested Jumper Mid",          "hard_cap": 45, "notes": "Contested mid-range"},
    {"order": 25, "name": "Contested Jumper Three",        "hard_cap": 40, "notes": "Contested 3PT"},
    {"order": 26, "name": "Step-Back Jumper Mid",          "hard_cap": 40, "notes": "LOCKED cap=40"},
    {"order": 27, "name": "Step-Back Jumper Three",        "hard_cap": 35, "notes": "LOCKED cap=35"},
    {"order": 28, "name": "Spin Jumper",                   "hard_cap": 45, "notes": "Spin into jumper"},
    {"order": 29, "name": "Transition Pull-Up Three",      "hard_cap": 45, "notes": "Transition pull-up 3PT"},
    {"order": 30, "name": "Dribble Pull-Up Mid",           "hard_cap": 50, "notes": "Pull-up mid off dribble"},
    {"order": 31, "name": "Dribble Pull-Up Three",         "hard_cap": 40, "notes": "Pull-up 3PT off dribble"},
    {"order": 32, "name": "Drive",                         "hard_cap": 60, "notes": "Attack off dribble"},
    {"order": 33, "name": "Spot-Up Drive",                 "hard_cap": 55, "notes": "Drive from catch"},
    {"order": 34, "name": "Off-Screen Drive",              "hard_cap": 50, "notes": "Drive after screen"},
    {"order": 35, "name": "Use Glass",                     "hard_cap": 55, "notes": "Backboard usage"},
    {"order": 36, "name": "Driving Layup",                 "hard_cap": 60, "notes": "Driving layup frequency"},
    {"order": 37, "name": "Step Through Shot",             "hard_cap": 45, "notes": "Step-through finishing"},
    {"order": 38, "name": "Spin Layup",                    "hard_cap": 55, "notes": "Spin into layup"},
    {"order": 39, "name": "Eurostep Layup",                "hard_cap": 55, "notes": "Euro-step finishing"},
    {"order": 40, "name": "Hop Step Layup",                "hard_cap": 55, "notes": "Hop-step finishing"},
    {"order": 41, "name": "Floater",                       "hard_cap": 55, "notes": "Floater/runner"},
    {"order": 42, "name": "Stand & Dunk",                  "hard_cap": 60, "notes": "Standing dunk frequency"},
    {"order": 43, "name": "Drive & Dunk",                  "hard_cap": 60, "notes": "Driving dunk frequency"},
    {"order": 44, "name": "Flashy Dunk",                   "hard_cap": 55, "notes": "LOCKED cap=55"},
    {"order": 45, "name": "Alley-Oop",                     "hard_cap": 55, "notes": "LOCKED cap=55"},
    {"order": 46, "name": "Putback",                       "hard_cap": 55, "notes": "LOCKED cap=55"},
    {"order": 47, "name": "Crash",                         "hard_cap": 55, "notes": "Offensive rebound crash"},
    {"order": 48, "name": "Drive Right",                   "hard_cap": 80, "notes": "Directional drive pref"},
    {"order": 49, "name": "Triple Threat Pump Fake",       "hard_cap": 60, "notes": "TT pump fake"},
    {"order": 50, "name": "Triple Threat Jab Step",        "hard_cap": 60, "notes": "TT jab step"},
    {"order": 51, "name": "Triple Threat Idle",            "hard_cap": 40, "notes": "TT idle"},
    {"order": 52, "name": "Triple Threat Shoot",           "hard_cap": 55, "notes": "TT shoot"},
    {"order": 53, "name": "Set Up with Size Up",           "hard_cap": 55, "notes": "Size-up dribble setup"},
    {"order": 54, "name": "Set Up with Hesitation",        "hard_cap": 55, "notes": "Hesitation dribble setup"},
    {"order": 55, "name": "No Set Up Dribble",             "hard_cap": 35, "notes": "ABSOLUTE cap=35"},
    {"order": 56, "name": "Drive and Crossover",           "hard_cap": 55, "notes": "Crossover on drive"},
    {"order": 57, "name": "Drive and Double Crossover",    "hard_cap": 55, "notes": "Double crossover on drive"},
    {"order": 58, "name": "Drive and Spin",                "hard_cap": 55, "notes": "Spin on drive"},
    {"order": 59, "name": "Drive and Half Spin",           "hard_cap": 55, "notes": "Half spin on drive"},
    {"order": 60, "name": "Drive and Step Back",           "hard_cap": 55, "notes": "Step back on drive"},
    {"order": 61, "name": "Drive and Behind the Back",     "hard_cap": 55, "notes": "BTB on drive"},
    {"order": 62, "name": "Drive and Dribble Hesitation",  "hard_cap": 55, "notes": "Hesitation on drive"},
    {"order": 63, "name": "Drive and In and Out",          "hard_cap": 55, "notes": "In & out on drive"},
    {"order": 64, "name": "No Drive & Dribble Move",       "hard_cap": 85, "notes": "Straight-line drive pref"},
    {"order": 65, "name": "Attack Strong on Drive",        "hard_cap": 60, "notes": "Draw contact on drive"},
    {"order": 66, "name": "Dish to Open Man",              "hard_cap": 55, "notes": "Pass-first tendency"},
    {"order": 67, "name": "Flashy Pass",                   "hard_cap": 55, "notes": "Behind-back/no-look pass"},
    {"order": 68, "name": "Alley-Oop Pass",                "hard_cap": 55, "notes": "Lob pass tendency"},
    {"order": 69, "name": "Roll vs Pop",                   "hard_cap": 85, "notes": "PnR roll preference"},
    {"order": 70, "name": "Transition Spot Up vs Cut to Basket", "hard_cap": 85, "notes": "Transition off-ball"},
    {"order": 71, "name": "Isolation vs Elite",            "hard_cap": 55, "notes": "ISO vs elite defenders"},
    {"order": 72, "name": "Isolation vs Good",             "hard_cap": 55, "notes": "ISO vs good defenders"},
    {"order": 73, "name": "Isolation vs Average",          "hard_cap": 55, "notes": "ISO vs avg defenders"},
    {"order": 74, "name": "Isolation vs Poor",             "hard_cap": 55, "notes": "ISO vs poor defenders"},
    {"order": 75, "name": "Play Discipline",               "hard_cap": 75, "notes": "Decision-making quality"},
    {"order": 76, "name": "Post Up",                       "hard_cap": 60, "notes": "Post-up frequency"},
    {"order": 77, "name": "Post Back Down",                "hard_cap": 60, "notes": "Back-down post move"},
    {"order": 78, "name": "Post Aggressive Back Down",     "hard_cap": 60, "notes": "Aggressive back-down"},
    {"order": 79, "name": "Post Face Up",                  "hard_cap": 55, "notes": "Face-up from post"},
    {"order": 80, "name": "Post Spin",                     "hard_cap": 60, "notes": "Post spin move"},
    {"order": 81, "name": "Post Drive",                    "hard_cap": 60, "notes": "Post drive move"},
    {"order": 82, "name": "Post Drop Step",                "hard_cap": 60, "notes": "Drop step move"},
    {"order": 83, "name": "Shoot From Post",               "hard_cap": 60, "notes": "Shoot from post"},
    {"order": 84, "name": "Post Hook Left",                "hard_cap": 60, "notes": "Left hook from post"},
    {"order": 85, "name": "Post Hook Right",               "hard_cap": 60, "notes": "Right hook from post"},
    {"order": 86, "name": "Post Fade Left",                "hard_cap": 60, "notes": "Left fade from post"},
    {"order": 87, "name": "Post Fade Right",               "hard_cap": 60, "notes": "Right fade from post"},
    {"order": 88, "name": "Post Shimmy Shot",              "hard_cap": 60, "notes": "Shimmy shot from post"},
    {"order": 89, "name": "Post Hop Shot",                 "hard_cap": 60, "notes": "Hop shot from post"},
    {"order": 90, "name": "Post Step Back Shot",           "hard_cap": 60, "notes": "Step-back from post"},
    {"order": 91, "name": "Post Up and Under",             "hard_cap": 60, "notes": "Up-and-under from post"},
    {"order": 92, "name": "Takes Charge",                  "hard_cap": 60, "notes": "Charge drawing tendency"},
    {"order": 93, "name": "Foul",                          "hard_cap": 60, "notes": "Foul drawing on offense"},
    {"order": 94, "name": "Hard Foul",                     "hard_cap": 55, "notes": "Intentional hard foul"},
    {"order": 95, "name": "Pass Interception",             "hard_cap": 60, "notes": "Deflection tendency"},
    {"order": 96, "name": "On-Ball Steal",                 "hard_cap": 60, "notes": "On-ball steal attempt"},
    {"order": 97, "name": "Blocked Shot",                  "hard_cap": 60, "notes": "Block attempt tendency"},
    {"order": 98, "name": "Contest Shot",                  "hard_cap": 60, "notes": "Contest shot tendency"},
]

HARD_CAPS = {t["name"]: t["hard_cap"] for t in TENDENCIES}

LOCKED_ABSOLUTE = {"No Set Up Dribble": 35}

LOCKED_CAPS = {
    "Step-Back Jumper Mid":   40,
    "Step-Back Jumper Three": 35,
    "Flashy Dunk":            55,
    "Alley-Oop":              55,
    "Putback":                55,
}

RELATIONAL_RULES = [
    ("Spot-Up Shot Mid", "<=", "Shot Mid"),
    ("Off-Screen Mid",   "<=", "Shot Mid"),
]

POSITION_GROUPS = {
    "guard": ["PG", "SG"],
    "wing":  ["SF", "SG"],
    "big":   ["PF", "C"],
}

TENDENCY_ORDER = [t["name"] for t in TENDENCIES]
